version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gogo-main-db-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: shop_inventory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gogo-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: gogo-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - gogo-net

  jenkins:
    build:
      context: ../smart-retail-config/jenkins
      dockerfile: Dockerfile
    container_name: gogo-jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8081:8080"         # Jenkins UI
      - "50000:50000"       # Agent communication
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins_data:/var/jenkins_home            # שומר את ה־Jenkins state
      - /var/run/docker.sock:/var/run/docker.sock   # כדי להריץ docker מתוך Jenkins
      - ../smart-retail-config/kubeconfig:/root/.kube/config  # kubeconfig חיבור ל־minikube
    privileged: true
    networks:
      - gogo-net

volumes:
  pgdata:
  pgadmin-data:

networks:
  gogo-net:
    driver: bridge
