# Use version 3.8 of Docker Compose file format
version: '3.8'

services:
  # PostgreSQL database service
  db:
    image: postgres:15
    container_name: gogo-main-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: shop_inventory
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Volume for persistent DB data
    networks:
      - gogo-net # All services here connect to this primary 'gogo-net'

  # pgAdmin 4 service
  pgadmin:
    image: dpage/pgadmin4
    container_name: gogo-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin # Volume for persistent pgAdmin data
    networks:
      - gogo-net

  # Main Backend service
  # The build context points to the 'backend' subdirectory relative to this docker-compose.yml.
  backend:
    build:
      context: ./backend # Points to: .../smart-retail-dev/backend/
    container_name: gogo-backend
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/shop_inventory
    depends_on:
      - db # Ensure DB starts before backend
    networks:
      - gogo-net

  # DR Backend service
  dr-backend:
    image: rani19/backend:latest
    container_name: gogo-dr-backend
    restart: unless-stopped
    ports:
      - "5002:5000" # DR Backend exposed on host port 5002
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/shop_inventory
    networks:
      - gogo-net

  # DR Frontend service
  dr-frontend:
    image: rani19/gogo-main-frontend:latest
    container_name: gogo-dr-frontend
    restart: unless-stopped
    ports:
      - "3002:80" # DR Frontend exposed on host port 3002
    networks:
      - gogo-net

# Define Docker volumes for persistent data
volumes:
  pgdata: # For PostgreSQL data
  pgadmin-data: # For pgAdmin data

# Define the single custom bridge network for all services
networks:
  gogo-net:
    # Changed from 'driver: bridge' to 'external: true'
    # This tells Docker Compose to connect to a network that already exists and is named 'gogo-net'.
    external: true
